/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CategoryDescription: typeof import('./src/components/parts/CategoryDescription/CategoryDescription.vue')['default']
    CategoryEditForm: typeof import('./src/components/parts/CategoryEditForm/CategoryEditForm.vue')['default']
    CategoryTable: typeof import('./src/components/parts/CategoryList/CategoryTable.vue')['default']
    DangerButton: typeof import('./src/components/parts/Button/DangerButton.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ImageCard: typeof import('./src/components/parts/ImageCard/ImageCard.vue')['default']
    ImageList: typeof import('./src/components/parts/ImageList/ImageList.vue')['default']
    OutlinedButton: typeof import('./src/components/parts/Button/OutlinedButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextInput: typeof import('./src/components/parts/TextInput/TextInput.vue')['default']
    TheHeader: typeof import('./src/components/parts/TheHeader/TheHeader.vue')['default']
    WarningButton: typeof import('./src/components/parts/Button/WarningButton.vue')['default']
  }
}
