/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CategoryDescription: typeof import('./src/components/parts/CategoryDescription/CategoryDescription.vue')['default']
    'CategoryDescription.bk': typeof import("./src/components/parts/CategoryDescription/CategoryDescription.vue")["default"]
    CategoryTable: typeof import('./src/components/parts/CategoryList/CategoryTable.vue')['default']
    DangerButton: typeof import('./src/components/parts/Button/DangerButton.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ImageCard: typeof import('./src/components/parts/ImageCard/ImageCard.vue')['default']
    ImageList: typeof import('./src/components/parts/ImageList/ImageList.vue')['default']
    OutlinedButton: typeof import('./src/components/parts/Button/OutlinedButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WarningButton: typeof import('./src/components/parts/Button/WarningButton.vue')['default']
  }
}
